#!/bin/bash

echo 'checkout tag for current release for upstream op'
echo 'apply panda patch patch -p1 < 0.XXXX-panda.patch'
echo 'build_all.sh'
echo 'copy panda.bin.signed to /data'
echo ''
echo 'checkout release3'
echo 'rm panda/board/obj/*'
echo 'cp /data/panda.bin.signed panda/board/obj'
echo ''
echo 'apply remaining patches: patch -p1 < patchfile'
echo 'git checkout -b [release]-release3-gm-ascm-interceptor-volt'
echo 'git remote add fork git@github.com:andrewcopenpilot/openpilot.git'
echo './github_init_ssh.sh'
echo ''
echo 'git add -f panda/board/obj/panda.bin.signed'
echo 'git add selfdrive/car/car_helpers.py'
echo 'git add selfdrive/car/gm/carcontroller.py'
echo 'git add selfdrive/car/gm/interface.py'
echo 'git add selfdrive/car/gm/values.py'
echo ''
echo 'git push fork'
